import { CanvasComponent, ComponentType, DevicePreset } from '../types';

export const DEVICE_PRESETS: DevicePreset[] = [
  {
    id: 'iphone',
    name: 'iPhone 15 Pro',
    width: 393,
    height: 852,
    type: 'iOS',
    notchType: 'dynamic-island',
    borderRadius: 48,
  },
  {
    id: 'android',
    name: 'Google Pixel 8',
    width: 412,
    height: 915,
    type: 'Android',
    notchType: 'punch-hole',
    borderRadius: 40,
  },
  {
    id: 'tablet',
    name: 'iPad Air 11"',
    width: 820,
    height: 1180,
    type: 'Tablet',
    notchType: 'none',
    borderRadius: 28,
  },
  {
    id: 'desktop',
    name: 'Desktop Web',
    width: 1280,
    height: 800,
    type: 'Desktop',
    notchType: 'none',
    borderRadius: 16,
  },
  {
    id: 'custom',
    name: 'Personalizado',
    width: 375,
    height: 812,
    type: 'Custom',
    notchType: 'none',
    borderRadius: 32,
  },
];

export const POPULAR_ICONS = [
  'Heart',
  'Star',
  'Home',
  'User',
  'Settings',
  'Search',
  'ShoppingBag',
  'Bell',
  'Camera',
  'MapPin',
  'Calendar',
  'Mail',
  'Phone',
  'Lock',
  'Check',
  'Plus',
  'X',
  'ArrowRight',
  'ArrowLeft',
  'ChevronRight',
  'Sliders',
  'Filter',
  'Share2',
  'Bookmark',
  'MessageSquare',
  'Play',
  'Pause',
  'Music',
  'Volume2',
  'Eye',
  'Image',
  'Globe',
  'CreditCard',
  'Zap',
  'Shield',
  'TrendingUp',
  'Radio',
  'Cpu',
  'Compass',
  'Award',
  'Smile',
];

export interface ComponentMetadata {
  type: ComponentType;
  label: string;
  category: 'basic' | 'layout' | 'input' | 'navigation' | 'media' | 'advanced';
  icon: string;
  defaultWidth: number;
  defaultHeight: number;
  defaultComponent: Partial<CanvasComponent>;
}

export const COMPONENT_CATALOG: ComponentMetadata[] = [
  // BASIC
  {
    type: 'text',
    label: 'Texto',
    category: 'basic',
    icon: 'Type',
    defaultWidth: 200,
    defaultHeight: 32,
    defaultComponent: {
      content: 'Título do Elemento',
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: '600',
      color: '#0F172A',
      textAlign: 'left',
      backgroundColor: 'transparent',
    },
  },
  {
    type: 'button',
    label: 'Botão Principal',
    category: 'basic',
    icon: 'MousePointerClick',
    defaultWidth: 280,
    defaultHeight: 48,
    defaultComponent: {
      content: 'Confirmar Ação',
      fontFamily: 'Inter',
      fontSize: 15,
      fontWeight: '600',
      color: '#FFFFFF',
      textAlign: 'center',
      backgroundColor: '#2563EB',
      border: {
        style: 'none',
        color: 'transparent',
        width: 0,
        radiusTopLeft: 12,
        radiusTopRight: 12,
        radiusBottomRight: 12,
        radiusBottomLeft: 12,
        isRadiusLinked: true,
      },
      shadow: {
        enabled: true,
        color: 'rgba(37, 99, 235, 0.3)',
        x: 0,
        y: 4,
        blur: 12,
        spread: 0,
        inset: false,
      },
    },
  },
  {
    type: 'image',
    label: 'Imagem',
    category: 'basic',
    icon: 'Image',
    defaultWidth: 280,
    defaultHeight: 180,
    defaultComponent: {
      imageSrc: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600&auto=format&fit=crop&q=80',
      objectFit: 'cover',
      backgroundColor: '#E2E8F0',
      border: {
        style: 'none',
        color: '#E2E8F0',
        width: 1,
        radiusTopLeft: 16,
        radiusTopRight: 16,
        radiusBottomRight: 16,
        radiusBottomLeft: 16,
        isRadiusLinked: true,
      },
    },
  },
  {
    type: 'icon',
    label: 'Ícone',
    category: 'basic',
    icon: 'Smile',
    defaultWidth: 44,
    defaultHeight: 44,
    defaultComponent: {
      iconName: 'Heart',
      color: '#EC4899',
      backgroundColor: '#FCE7F3',
      border: {
        style: 'none',
        color: 'transparent',
        width: 0,
        radiusTopLeft: 22,
        radiusTopRight: 22,
        radiusBottomRight: 22,
        radiusBottomLeft: 22,
        isRadiusLinked: true,
      },
    },
  },
  {
    type: 'badge',
    label: 'Badge',
    category: 'basic',
    icon: 'Tag',
    defaultWidth: 80,
    defaultHeight: 26,
    defaultComponent: {
      content: 'NOVO',
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: '700',
      color: '#15803D',
      backgroundColor: '#DCFCE7',
      textAlign: 'center',
      border: {
        style: 'none',
        color: 'transparent',
        width: 0,
        radiusTopLeft: 13,
        radiusTopRight: 13,
        radiusBottomRight: 13,
        radiusBottomLeft: 13,
        isRadiusLinked: true,
      },
    },
  },
  {
    type: 'chip',
    label: 'Chip / Tag',
    category: 'basic',
    icon: 'Bookmark',
    defaultWidth: 110,
    defaultHeight: 34,
    defaultComponent: {
      content: 'Tecnologia',
      iconName: 'Zap',
      fontFamily: 'Inter',
      fontSize: 13,
      fontWeight: '500',
      color: '#475569',
      backgroundColor: '#F1F5F9',
      textAlign: 'center',
      border: {
        style: 'solid',
        color: '#E2E8F0',
        width: 1,
        radiusTopLeft: 20,
        radiusTopRight: 20,
        radiusBottomRight: 20,
        radiusBottomLeft: 20,
        isRadiusLinked: true,
      },
    },
  },
  {
    type: 'avatar',
    label: 'Avatar',
    category: 'basic',
    icon: 'User',
    defaultWidth: 64,
    defaultHeight: 64,
    defaultComponent: {
      imageSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      objectFit: 'cover',
      backgroundColor: '#CBD5E1',
      border: {
        style: 'solid',
        color: '#FFFFFF',
        width: 2,
        radiusTopLeft: 32,
        radiusTopRight: 32,
        radiusBottomRight: 32,
        radiusBottomLeft: 32,
        isRadiusLinked: true,
      },
      shadow: {
        enabled: true,
        color: 'rgba(0,0,0,0.1)',
        x: 0,
        y: 2,
        blur: 8,
        spread: 0,
        inset: false,
      },
    },
  },
  {
    type: 'divider',
    label: 'Divisor',
    category: 'basic',
    icon: 'Minus',
    defaultWidth: 320,
    defaultHeight: 2,
    defaultComponent: {
      backgroundColor: '#E2E8F0',
    },
  },

  // INPUTS
  {
    type: 'input',
    label: 'Campo de Texto',
    category: 'input',
    icon: 'SquareCode',
    defaultWidth: 320,
    defaultHeight: 52,
    defaultComponent: {
      placeholder: 'Digite seu e-mail...',
      content: '',
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '400',
      color: '#0F172A',
      backgroundColor: '#F8FAFC',
      border: {
        style: 'solid',
        color: '#E2E8F0',
        width: 1.5,
        radiusTopLeft: 12,
        radiusTopRight: 12,
        radiusBottomRight: 12,
        radiusBottomLeft: 12,
        isRadiusLinked: true,
      },
      iconName: 'Mail',
      iconPosition: 'left',
    },
  },
  {
    type: 'password',
    label: 'Campo Senha',
    category: 'input',
    icon: 'Lock',
    defaultWidth: 320,
    defaultHeight: 52,
    defaultComponent: {
      placeholder: '••••••••',
      content: '',
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '400',
      color: '#0F172A',
      backgroundColor: '#F8FAFC',
      border: {
        style: 'solid',
        color: '#E2E8F0',
        width: 1.5,
        radiusTopLeft: 12,
        radiusTopRight: 12,
        radiusBottomRight: 12,
        radiusBottomLeft: 12,
        isRadiusLinked: true,
      },
      iconName: 'Lock',
      iconPosition: 'left',
    },
  },
  {
    type: 'checkbox',
    label: 'Checkbox',
    category: 'input',
    icon: 'CheckSquare',
    defaultWidth: 220,
    defaultHeight: 28,
    defaultComponent: {
      content: 'Lembrar de mim',
      checked: true,
      color: '#0F172A',
      backgroundColor: '#2563EB',
      fontSize: 14,
    },
  },
  {
    type: 'switch',
    label: 'Switch Alternador',
    category: 'input',
    icon: 'ToggleRight',
    defaultWidth: 240,
    defaultHeight: 32,
    defaultComponent: {
      content: 'Notificações Push',
      checked: true,
      color: '#0F172A',
      backgroundColor: '#2563EB',
      fontSize: 14,
    },
  },
  {
    type: 'slider',
    label: 'Barra Slider',
    category: 'input',
    icon: 'Sliders',
    defaultWidth: 280,
    defaultHeight: 36,
    defaultComponent: {
      value: 65,
      minValue: 0,
      maxValue: 100,
      backgroundColor: '#2563EB',
    },
  },
  {
    type: 'progressbar',
    label: 'Barra Progresso',
    category: 'input',
    icon: 'BarChart2',
    defaultWidth: 280,
    defaultHeight: 12,
    defaultComponent: {
      value: 75,
      backgroundColor: '#2563EB',
      border: {
        style: 'none',
        color: 'transparent',
        width: 0,
        radiusTopLeft: 6,
        radiusTopRight: 6,
        radiusBottomRight: 6,
        radiusBottomLeft: 6,
        isRadiusLinked: true,
      },
    },
  },

  // LAYOUT
  {
    type: 'container',
    label: 'Container Bloco',
    category: 'layout',
    icon: 'Square',
    defaultWidth: 320,
    defaultHeight: 160,
    defaultComponent: {
      backgroundColor: '#FFFFFF',
      border: {
        style: 'solid',
        color: '#E2E8F0',
        width: 1,
        radiusTopLeft: 16,
        radiusTopRight: 16,
        radiusBottomRight: 16,
        radiusBottomLeft: 16,
        isRadiusLinked: true,
      },
      shadow: {
        enabled: true,
        color: 'rgba(0,0,0,0.04)',
        x: 0,
        y: 4,
        blur: 16,
        spread: 0,
        inset: false,
      },
    },
  },
  {
    type: 'card',
    label: 'Card Ilustrado',
    category: 'layout',
    icon: 'LayoutGrid',
    defaultWidth: 320,
    defaultHeight: 220,
    defaultComponent: {
      content: 'Título do Card Especial',
      backgroundColor: '#FFFFFF',
      imageSrc: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&auto=format&fit=crop&q=80',
      border: {
        style: 'solid',
        color: '#F1F5F9',
        width: 1,
        radiusTopLeft: 20,
        radiusTopRight: 20,
        radiusBottomRight: 20,
        radiusBottomLeft: 20,
        isRadiusLinked: true,
      },
      shadow: {
        enabled: true,
        color: 'rgba(15, 23, 42, 0.08)',
        x: 0,
        y: 8,
        blur: 24,
        spread: -4,
        inset: false,
      },
    },
  },
  {
    type: 'row',
    label: 'Linha Horizontal (Row)',
    category: 'layout',
    icon: 'Rows',
    defaultWidth: 320,
    defaultHeight: 60,
    defaultComponent: {
      backgroundColor: '#F8FAFC',
      border: {
        style: 'dashed',
        color: '#CBD5E1',
        width: 1,
        radiusTopLeft: 12,
        radiusTopRight: 12,
        radiusBottomRight: 12,
        radiusBottomLeft: 12,
        isRadiusLinked: true,
      },
    },
  },
  {
    type: 'column',
    label: 'Coluna Vertical (Col)',
    category: 'layout',
    icon: 'Columns',
    defaultWidth: 160,
    defaultHeight: 240,
    defaultComponent: {
      backgroundColor: '#F8FAFC',
      border: {
        style: 'dashed',
        color: '#CBD5E1',
        width: 1,
        radiusTopLeft: 12,
        radiusTopRight: 12,
        radiusBottomRight: 12,
        radiusBottomLeft: 12,
        isRadiusLinked: true,
      },
    },
  },

  // NAVIGATION & BARS
  {
    type: 'top_app_bar',
    label: 'Top App Bar',
    category: 'navigation',
    icon: 'PanelTop',
    defaultWidth: 393,
    defaultHeight: 64,
    defaultComponent: {
      content: 'Minha Aplicação',
      fontFamily: 'Inter',
      fontSize: 18,
      fontWeight: '700',
      color: '#0F172A',
      backgroundColor: '#FFFFFF',
      iconName: 'Bell',
      border: {
        style: 'solid',
        color: '#F1F5F9',
        width: 1,
        radiusTopLeft: 0,
        radiusTopRight: 0,
        radiusBottomRight: 0,
        radiusBottomLeft: 0,
        isRadiusLinked: true,
      },
    },
  },
  {
    type: 'bottom_nav',
    label: 'Bottom Navigation',
    category: 'navigation',
    icon: 'PanelBottom',
    defaultWidth: 393,
    defaultHeight: 72,
    defaultComponent: {
      backgroundColor: '#FFFFFF',
      color: '#2563EB',
      items: ['Início', 'Buscar', 'Favoritos', 'Perfil'],
      border: {
        style: 'solid',
        color: '#E2E8F0',
        width: 1,
        radiusTopLeft: 24,
        radiusTopRight: 24,
        radiusBottomRight: 0,
        radiusBottomLeft: 0,
        isRadiusLinked: false,
      },
      shadow: {
        enabled: true,
        color: 'rgba(0,0,0,0.06)',
        x: 0,
        y: -4,
        blur: 16,
        spread: 0,
        inset: false,
      },
    },
  },
  {
    type: 'floating_button',
    label: 'Floating Action Button',
    category: 'navigation',
    icon: 'PlusCircle',
    defaultWidth: 56,
    defaultHeight: 56,
    defaultComponent: {
      iconName: 'Plus',
      color: '#FFFFFF',
      backgroundColor: '#2563EB',
      border: {
        style: 'none',
        color: 'transparent',
        width: 0,
        radiusTopLeft: 28,
        radiusTopRight: 28,
        radiusBottomRight: 28,
        radiusBottomLeft: 28,
        isRadiusLinked: true,
      },
      shadow: {
        enabled: true,
        color: 'rgba(37, 99, 235, 0.4)',
        x: 0,
        y: 6,
        blur: 16,
        spread: 0,
        inset: false,
      },
    },
  },
  {
    type: 'tabs',
    label: 'Abas (Tabs)',
    category: 'navigation',
    icon: 'FolderKanban',
    defaultWidth: 340,
    defaultHeight: 44,
    defaultComponent: {
      items: ['Visão Geral', 'Atividades', 'Ajustes'],
      backgroundColor: '#F1F5F9',
      color: '#2563EB',
      fontSize: 13,
      fontWeight: '600',
      border: {
        style: 'none',
        color: 'transparent',
        width: 0,
        radiusTopLeft: 12,
        radiusTopRight: 12,
        radiusBottomRight: 12,
        radiusBottomLeft: 12,
        isRadiusLinked: true,
      },
    },
  },

  // MEDIA & ADVANCED
  {
    type: 'carousel',
    label: 'Carrossel de Banners',
    category: 'media',
    icon: 'GalleryHorizontal',
    defaultWidth: 340,
    defaultHeight: 160,
    defaultComponent: {
      backgroundColor: '#0F172A',
      imageSrc: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
      border: {
        style: 'none',
        color: 'transparent',
        width: 0,
        radiusTopLeft: 20,
        radiusTopRight: 20,
        radiusBottomRight: 20,
        radiusBottomLeft: 20,
        isRadiusLinked: true,
      },
    },
  },
  {
    type: 'map',
    label: 'Mapa Interativo',
    category: 'advanced',
    icon: 'Map',
    defaultWidth: 340,
    defaultHeight: 180,
    defaultComponent: {
      content: 'São Paulo, Brasil',
      backgroundColor: '#E0F2FE',
      border: {
        style: 'solid',
        color: '#BAE6FD',
        width: 1,
        radiusTopLeft: 16,
        radiusTopRight: 16,
        radiusBottomRight: 16,
        radiusBottomLeft: 16,
        isRadiusLinked: true,
      },
    },
  },
  {
    type: 'calendar',
    label: 'Calendário',
    category: 'advanced',
    icon: 'Calendar',
    defaultWidth: 320,
    defaultHeight: 220,
    defaultComponent: {
      backgroundColor: '#FFFFFF',
      border: {
        style: 'solid',
        color: '#E2E8F0',
        width: 1,
        radiusTopLeft: 16,
        radiusTopRight: 16,
        radiusBottomRight: 16,
        radiusBottomLeft: 16,
        isRadiusLinked: true,
      },
      shadow: {
        enabled: true,
        color: 'rgba(0,0,0,0.04)',
        x: 0,
        y: 4,
        blur: 12,
        spread: 0,
        inset: false,
      },
    },
  },
  {
    type: 'video',
    label: 'Player de Vídeo',
    category: 'media',
    icon: 'Video',
    defaultWidth: 320,
    defaultHeight: 180,
    defaultComponent: {
      content: 'Vídeo Demonstrativo',
      backgroundColor: '#0F172A',
      border: {
        style: 'none',
        color: 'transparent',
        width: 0,
        radiusTopLeft: 16,
        radiusTopRight: 16,
        radiusBottomRight: 16,
        radiusBottomLeft: 16,
        isRadiusLinked: true,
      },
    },
  },
  {
    type: 'audio',
    label: 'Player de Áudio',
    category: 'media',
    icon: 'Music',
    defaultWidth: 320,
    defaultHeight: 68,
    defaultComponent: {
      content: 'Podcast Ep. 42 - Design Systems',
      backgroundColor: '#1E293B',
      color: '#FFFFFF',
      iconName: 'Play',
      border: {
        style: 'none',
        color: 'transparent',
        width: 0,
        radiusTopLeft: 16,
        radiusTopRight: 16,
        radiusBottomRight: 16,
        radiusBottomLeft: 16,
        isRadiusLinked: true,
      },
    },
  },
  {
    type: 'modal',
    label: 'Modal / Sheet',
    category: 'advanced',
    icon: 'Maximize2',
    defaultWidth: 320,
    defaultHeight: 200,
    defaultComponent: {
      content: 'Atenção! Confirma esta alteração?',
      backgroundColor: '#FFFFFF',
      border: {
        style: 'solid',
        color: '#E2E8F0',
        width: 1,
        radiusTopLeft: 24,
        radiusTopRight: 24,
        radiusBottomRight: 24,
        radiusBottomLeft: 24,
        isRadiusLinked: true,
      },
      shadow: {
        enabled: true,
        color: 'rgba(0,0,0,0.2)',
        x: 0,
        y: 12,
        blur: 32,
        spread: 0,
        inset: false,
      },
    },
  },
];

export function createNewComponent(
  type: ComponentType,
  x: number,
  y: number,
  customZIndex: number = 10
): CanvasComponent {
  const catalogItem = COMPONENT_CATALOG.find((c) => c.type === type) || COMPONENT_CATALOG[0];
  const defaults = catalogItem.defaultComponent;

  return {
    id: `comp_${Date.now()}_${Math.random().toString(36).substr(2, 5)}`,
    name: `${catalogItem.label} ${Math.floor(Math.random() * 90 + 10)}`,
    type: catalogItem.type,
    category: catalogItem.category,

    x,
    y,
    width: catalogItem.defaultWidth,
    height: catalogItem.defaultHeight,
    rotation: 0,
    zIndex: customZIndex,
    opacity: 1,
    locked: false,
    hidden: false,

    paddingTop: 8,
    paddingRight: 8,
    paddingBottom: 8,
    paddingLeft: 8,

    fontFamily: defaults.fontFamily || 'Inter',
    fontSize: defaults.fontSize || 14,
    fontWeight: defaults.fontWeight || '400',
    color: defaults.color || '#0F172A',
    textAlign: defaults.textAlign || 'left',
    letterSpacing: 0,
    lineHeight: 1.2,

    backgroundColor: defaults.backgroundColor || '#FFFFFF',
    gradient: defaults.gradient || {
      enabled: false,
      type: 'linear',
      angle: 90,
      startColor: '#2563EB',
      endColor: '#7C3AED',
    },
    border: defaults.border || {
      style: 'none',
      color: '#E2E8F0',
      width: 1,
      radiusTopLeft: 12,
      radiusTopRight: 12,
      radiusBottomRight: 12,
      radiusBottomLeft: 12,
      isRadiusLinked: true,
    },
    shadow: defaults.shadow || {
      enabled: false,
      color: 'rgba(0,0,0,0.1)',
      x: 0,
      y: 4,
      blur: 12,
      spread: 0,
      inset: false,
    },
    backdropBlur: 0,

    content: defaults.content,
    placeholder: defaults.placeholder,
    iconName: defaults.iconName,
    iconPosition: defaults.iconPosition || 'left',
    imageSrc: defaults.imageSrc,
    objectFit: defaults.objectFit || 'cover',
    checked: defaults.checked,
    value: defaults.value,
    minValue: defaults.minValue,
    maxValue: defaults.maxValue,
    items: defaults.items ? [...defaults.items] : undefined,

    interaction: {
      onClickAction: 'none',
    },

    // Universal Events System - automatically injected
    events: {},

    // Auto Layout Defaults
    autoLayout: type === 'row' || type === 'column' || type === 'grid',
    layoutDirection: type === 'row' ? 'horizontal' : type === 'column' ? 'vertical' : type === 'grid' ? 'grid' : 'none',
    layoutDistribution: 'start',
    layoutAlignment: 'start',
    itemGap: 8,
    gridColumns: 2,
    gridRowGap: 8,

    // Responsive Constraints Defaults
    constraints: {
      horizontal: 'left',
      vertical: 'top',
      fillParent: false,
      maintainAspectRatio: false,
    },
  };
}
