import { MasterComponent, CanvasComponent } from '../types';

export const DEFAULT_MASTER_CATEGORIES = [
  'Geral',
  'Cards',
  'Cabeçalhos',
  'Formulários',
  'Banners',
  'Navegação',
  'Modais',
];

// Helper to create starter component tree
function makeComp(
  id: string,
  name: string,
  type: any,
  category: any,
  x: number,
  y: number,
  width: number,
  height: number,
  overrides: Partial<CanvasComponent> = {}
): CanvasComponent {
  return {
    id,
    name,
    type,
    category,
    x,
    y,
    width,
    height,
    rotation: 0,
    zIndex: 1,
    opacity: 1,
    locked: false,
    hidden: false,
    paddingTop: 8,
    paddingRight: 8,
    paddingBottom: 8,
    paddingLeft: 8,
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: 'normal',
    color: '#334155',
    textAlign: 'left',
    letterSpacing: 0,
    lineHeight: 1.4,
    backgroundColor: 'transparent',
    gradient: { enabled: false, type: 'linear', angle: 90, startColor: '#3b82f6', endColor: '#8b5cf6' },
    border: { style: 'none', color: '#e2e8f0', width: 1, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
    shadow: { enabled: false, color: '#000000', x: 0, y: 2, blur: 4, spread: 0, inset: false },
    backdropBlur: 0,
    interaction: { onClickAction: 'none' },
    ...overrides,
  };
}

export const INITIAL_MASTER_COMPONENTS: MasterComponent[] = [
  {
    id: 'master_card_produto',
    name: 'Card de Produto',
    description: 'Card completo com imagem, título, avaliação e botão de compra',
    category: 'Cards',
    tags: ['card', 'produto', 'ecommerce', 'compra'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemCount: 5,
    width: 240,
    height: 280,
    isFavorite: true,
    rootComponent: makeComp(
      'mc_card_root',
      'Card Produto Container',
      'card',
      'layout',
      0,
      0,
      240,
      280,
      {
        backgroundColor: '#ffffff',
        border: { style: 'solid', color: '#e2e8f0', width: 1, radiusTopLeft: 16, radiusTopRight: 16, radiusBottomRight: 16, radiusBottomLeft: 16, isRadiusLinked: true },
        shadow: { enabled: true, color: 'rgba(0,0,0,0.06)', x: 0, y: 4, blur: 12, spread: 0, inset: false },
      }
    ),
    childrenComponents: [
      makeComp(
        'mc_card_img',
        'Imagem Produto',
        'image',
        'media',
        12,
        12,
        216,
        130,
        {
          parentId: 'mc_card_root',
          imageSrc: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=400&q=80',
          border: { style: 'none', color: '', width: 0, radiusTopLeft: 12, radiusTopRight: 12, radiusBottomRight: 12, radiusBottomLeft: 12, isRadiusLinked: true },
          objectFit: 'cover',
        }
      ),
      makeComp(
        'mc_card_title',
        'Título do Produto',
        'text',
        'basic',
        16,
        150,
        208,
        22,
        {
          parentId: 'mc_card_root',
          content: 'Fone Bluetooth Pro Max',
          fontSize: 15,
          fontWeight: 'bold',
          color: '#0f172a',
        }
      ),
      makeComp(
        'mc_card_price',
        'Preço',
        'text',
        'basic',
        16,
        178,
        120,
        20,
        {
          parentId: 'mc_card_root',
          content: 'R$ 299,90',
          fontSize: 16,
          fontWeight: 'bold',
          color: '#2563eb',
        }
      ),
      makeComp(
        'mc_card_btn',
        'Botão Comprar',
        'button',
        'basic',
        16,
        220,
        208,
        42,
        {
          parentId: 'mc_card_root',
          content: 'Adicionar ao Carrinho',
          backgroundColor: '#2563eb',
          color: '#ffffff',
          fontWeight: 'bold',
          border: { style: 'none', color: '', width: 0, radiusTopLeft: 10, radiusTopRight: 10, radiusBottomRight: 10, radiusBottomLeft: 10, isRadiusLinked: true },
        }
      ),
    ],
  },
  {
    id: 'master_app_bar',
    name: 'Cabeçalho Principal',
    description: 'Header mobile com título, ícones de navegação e foto de perfil',
    category: 'Cabeçalhos',
    tags: ['header', 'appbar', 'top', 'menu'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemCount: 4,
    width: 320,
    height: 60,
    isFavorite: true,
    rootComponent: makeComp(
      'mc_header_root',
      'Header Container',
      'row',
      'layout',
      0,
      0,
      320,
      60,
      {
        backgroundColor: '#0f172a',
        border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
      }
    ),
    childrenComponents: [
      makeComp(
        'mc_header_avatar',
        'Avatar Usuário',
        'avatar',
        'basic',
        16,
        12,
        36,
        36,
        {
          parentId: 'mc_header_root',
          imageSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
          border: { style: 'solid', color: '#3b82f6', width: 2, radiusTopLeft: 999, radiusTopRight: 999, radiusBottomRight: 999, radiusBottomLeft: 999, isRadiusLinked: true },
        }
      ),
      makeComp(
        'mc_header_title',
        'Saudação Título',
        'text',
        'basic',
        64,
        18,
        180,
        24,
        {
          parentId: 'mc_header_root',
          content: 'Olá, Gabriel 👋',
          fontSize: 16,
          fontWeight: 'bold',
          color: '#ffffff',
        }
      ),
      makeComp(
        'mc_header_badge',
        'Notificação',
        'badge',
        'basic',
        268,
        18,
        36,
        24,
        {
          parentId: 'mc_header_root',
          content: '3',
          backgroundColor: '#ef4444',
          color: '#ffffff',
          fontWeight: 'bold',
        }
      ),
    ],
  },
  {
    id: 'master_login_form',
    name: 'Formulário de Login',
    description: 'Campos estilizados de email, senha e botão entrar',
    category: 'Formulários',
    tags: ['login', 'form', 'input', 'senha'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemCount: 4,
    width: 280,
    height: 220,
    isFavorite: false,
    rootComponent: makeComp(
      'mc_form_root',
      'Form Login Container',
      'container',
      'layout',
      0,
      0,
      280,
      220,
      {
        backgroundColor: '#ffffff',
        border: { style: 'solid', color: '#e2e8f0', width: 1, radiusTopLeft: 16, radiusTopRight: 16, radiusBottomRight: 16, radiusBottomLeft: 16, isRadiusLinked: true },
        shadow: { enabled: true, color: 'rgba(0,0,0,0.05)', x: 0, y: 4, blur: 10, spread: 0, inset: false },
      }
    ),
    childrenComponents: [
      makeComp(
        'mc_form_email',
        'Campo Email',
        'input',
        'input',
        16,
        16,
        248,
        48,
        {
          parentId: 'mc_form_root',
          placeholder: 'Digite seu e-mail...',
          border: { style: 'solid', color: '#cbd5e1', width: 1, radiusTopLeft: 10, radiusTopRight: 10, radiusBottomRight: 10, radiusBottomLeft: 10, isRadiusLinked: true },
        }
      ),
      makeComp(
        'mc_form_pass',
        'Campo Senha',
        'password',
        'input',
        16,
        80,
        248,
        48,
        {
          parentId: 'mc_form_root',
          placeholder: 'Sua senha...',
          border: { style: 'solid', color: '#cbd5e1', width: 1, radiusTopLeft: 10, radiusTopRight: 10, radiusBottomRight: 10, radiusBottomLeft: 10, isRadiusLinked: true },
        }
      ),
      makeComp(
        'mc_form_btn',
        'Botão Entrar',
        'button',
        'basic',
        16,
        148,
        248,
        48,
        {
          parentId: 'mc_form_root',
          content: 'Entrar na Conta',
          backgroundColor: '#10b981',
          color: '#ffffff',
          fontWeight: 'bold',
          border: { style: 'none', color: '', width: 0, radiusTopLeft: 10, radiusTopRight: 10, radiusBottomRight: 10, radiusBottomLeft: 10, isRadiusLinked: true },
        }
      ),
    ],
  },
];
