import { DEVICE_PRESETS } from './componentTemplates';
import { Project, Screen } from '../types';

const defaultDevice = DEVICE_PRESETS[0]; // iPhone 15 Pro (393 x 852)

export interface TemplateProject {
  id: string;
  name: string;
  description: string;
  category: string;
  previewUrl: string;
  project: Project;
}

export const TEMPLATE_PROJECTS: TemplateProject[] = [
  {
    id: 'ecommerce_app',
    name: 'E-Commerce Fashion Store',
    description: 'Tela de vitrine, busca de produtos, banner promocional e navegação inferior.',
    category: 'Vendas & Lojas',
    previewUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=500&auto=format&fit=crop&q=80',
    project: {
      id: 'proj_ecommerce',
      name: 'E-Commerce Fashion Store',
      version: '1.0.0',
      device: defaultDevice,
      updatedAt: new Date().toISOString(),
      activeScreenId: 'scr_home',
      assets: [
        {
          id: 'asset_1',
          name: 'Modelo Moda Verão',
          url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
          type: 'image/jpeg',
          size: '240 KB',
          createdAt: new Date().toISOString(),
        },
        {
          id: 'asset_2',
          name: 'Tênis Esportivo Urban',
          url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
          type: 'image/jpeg',
          size: '310 KB',
          createdAt: new Date().toISOString(),
        },
      ],
      screens: [
        {
          id: 'scr_home',
          name: 'Início (Vitrine)',
          backgroundColor: '#F8FAFC',
          isInitialScreen: true,
          components: [
            // Top App Bar
            {
              id: 'c_topbar',
              name: 'Top Bar',
              type: 'top_app_bar',
              category: 'navigation',
              x: 0,
              y: 50,
              width: 393,
              height: 64,
              rotation: 0,
              zIndex: 10,
              opacity: 1,
              locked: true,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              fontFamily: 'Inter',
              fontSize: 20,
              fontWeight: '700',
              color: '#0F172A',
              textAlign: 'left',
              letterSpacing: -0.5,
              lineHeight: 1.2,
              backgroundColor: '#FFFFFF',
              content: 'Nova Coleção ✨',
              iconName: 'ShoppingBag',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: true, color: 'rgba(0,0,0,0.03)', x: 0, y: 2, blur: 8, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            // Search Input
            {
              id: 'c_search',
              name: 'Busca de Produtos',
              type: 'input',
              category: 'input',
              x: 20,
              y: 124,
              width: 353,
              height: 48,
              rotation: 0,
              zIndex: 9,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              fontFamily: 'Inter',
              fontSize: 14,
              fontWeight: '400',
              color: '#0F172A',
              placeholder: 'Buscar roupas, calçados...',
              iconName: 'Search',
              iconPosition: 'left',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#FFFFFF',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'solid', color: '#E2E8F0', width: 1, radiusTopLeft: 12, radiusTopRight: 12, radiusBottomRight: 12, radiusBottomLeft: 12, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            // Banner Hero
            {
              id: 'c_banner',
              name: 'Banner Promocional',
              type: 'card',
              category: 'layout',
              x: 20,
              y: 184,
              width: 353,
              height: 160,
              rotation: 0,
              zIndex: 8,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              fontFamily: 'Inter',
              fontSize: 16,
              fontWeight: '600',
              color: '#FFFFFF',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#1E1B4B',
              imageSrc: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&auto=format&fit=crop&q=80',
              gradient: { enabled: true, type: 'linear', angle: 180, startColor: 'rgba(0,0,0,0.1)', endColor: 'rgba(0,0,0,0.7)' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 20, radiusTopRight: 20, radiusBottomRight: 20, radiusBottomLeft: 20, isRadiusLinked: true },
              shadow: { enabled: true, color: 'rgba(0,0,0,0.15)', x: 0, y: 8, blur: 20, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            // Category Chips
            {
              id: 'c_chip1',
              name: 'Chip Verão',
              type: 'chip',
              category: 'basic',
              x: 20,
              y: 356,
              width: 100,
              height: 36,
              rotation: 0,
              zIndex: 7,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              content: '🔥 Ofertas',
              fontFamily: 'Inter',
              fontSize: 13,
              fontWeight: '600',
              color: '#2563EB',
              textAlign: 'center',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#EFF6FF',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 18, radiusTopRight: 18, radiusBottomRight: 18, radiusBottomLeft: 18, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_chip2',
              name: 'Chip Feminino',
              type: 'chip',
              category: 'basic',
              x: 130,
              y: 356,
              width: 105,
              height: 36,
              rotation: 0,
              zIndex: 7,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              content: 'Feminino',
              fontFamily: 'Inter',
              fontSize: 13,
              fontWeight: '500',
              color: '#475569',
              textAlign: 'center',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#FFFFFF',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'solid', color: '#E2E8F0', width: 1, radiusTopLeft: 18, radiusTopRight: 18, radiusBottomRight: 18, radiusBottomLeft: 18, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_chip3',
              name: 'Chip Calçados',
              type: 'chip',
              category: 'basic',
              x: 245,
              y: 356,
              width: 105,
              height: 36,
              rotation: 0,
              zIndex: 7,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              content: 'Calçados',
              fontFamily: 'Inter',
              fontSize: 13,
              fontWeight: '500',
              color: '#475569',
              textAlign: 'center',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#FFFFFF',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'solid', color: '#E2E8F0', width: 1, radiusTopLeft: 18, radiusTopRight: 18, radiusBottomRight: 18, radiusBottomLeft: 18, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            // Product Card 1
            {
              id: 'c_prod1',
              name: 'Card Produto Tênis',
              type: 'container',
              category: 'layout',
              x: 20,
              y: 408,
              width: 168,
              height: 220,
              rotation: 0,
              zIndex: 6,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              fontFamily: 'Inter',
              fontSize: 14,
              fontWeight: '400',
              color: '#0F172A',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#FFFFFF',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'solid', color: '#F1F5F9', width: 1, radiusTopLeft: 16, radiusTopRight: 16, radiusBottomRight: 16, radiusBottomLeft: 16, isRadiusLinked: true },
              shadow: { enabled: true, color: 'rgba(0,0,0,0.04)', x: 0, y: 4, blur: 12, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'navigate', targetScreenId: 'scr_detail', transitionEffect: 'slide_left' },
            },
            {
              id: 'c_prod1_img',
              name: 'Img Tênis',
              type: 'image',
              category: 'basic',
              x: 28,
              y: 416,
              width: 152,
              height: 120,
              rotation: 0,
              zIndex: 7,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              fontFamily: 'Inter',
              fontSize: 14,
              fontWeight: '400',
              color: '#0F172A',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#F1F5F9',
              imageSrc: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
              objectFit: 'cover',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 12, radiusTopRight: 12, radiusBottomRight: 12, radiusBottomLeft: 12, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'navigate', targetScreenId: 'scr_detail' },
            },
            {
              id: 'c_prod1_title',
              name: 'Nome Produto',
              type: 'text',
              category: 'basic',
              x: 28,
              y: 544,
              width: 152,
              height: 22,
              rotation: 0,
              zIndex: 7,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: 'Tênis Urban Runner',
              fontFamily: 'Inter',
              fontSize: 13,
              fontWeight: '600',
              color: '#0F172A',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_prod1_price',
              name: 'Preço Produto',
              type: 'text',
              category: 'basic',
              x: 28,
              y: 570,
              width: 152,
              height: 22,
              rotation: 0,
              zIndex: 7,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: 'R$ 299,90',
              fontFamily: 'Inter',
              fontSize: 15,
              fontWeight: '700',
              color: '#2563EB',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            // Product Card 2
            {
              id: 'c_prod2',
              name: 'Card Jaqueta Moda',
              type: 'container',
              category: 'layout',
              x: 204,
              y: 408,
              width: 168,
              height: 220,
              rotation: 0,
              zIndex: 6,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              fontFamily: 'Inter',
              fontSize: 14,
              fontWeight: '400',
              color: '#0F172A',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#FFFFFF',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'solid', color: '#F1F5F9', width: 1, radiusTopLeft: 16, radiusTopRight: 16, radiusBottomRight: 16, radiusBottomLeft: 16, isRadiusLinked: true },
              shadow: { enabled: true, color: 'rgba(0,0,0,0.04)', x: 0, y: 4, blur: 12, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_prod2_img',
              name: 'Img Jaqueta',
              type: 'image',
              category: 'basic',
              x: 212,
              y: 416,
              width: 152,
              height: 120,
              rotation: 0,
              zIndex: 7,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              fontFamily: 'Inter',
              fontSize: 14,
              fontWeight: '400',
              color: '#0F172A',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#F1F5F9',
              imageSrc: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
              objectFit: 'cover',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 12, radiusTopRight: 12, radiusBottomRight: 12, radiusBottomLeft: 12, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_prod2_title',
              name: 'Nome Jaqueta',
              type: 'text',
              category: 'basic',
              x: 212,
              y: 544,
              width: 152,
              height: 22,
              rotation: 0,
              zIndex: 7,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: 'Jaqueta Couro Style',
              fontFamily: 'Inter',
              fontSize: 13,
              fontWeight: '600',
              color: '#0F172A',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_prod2_price',
              name: 'Preço Jaqueta',
              type: 'text',
              category: 'basic',
              x: 212,
              y: 570,
              width: 152,
              height: 22,
              rotation: 0,
              zIndex: 7,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: 'R$ 459,00',
              fontFamily: 'Inter',
              fontSize: 15,
              fontWeight: '700',
              color: '#2563EB',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            // Bottom Nav
            {
              id: 'c_bottomnav',
              name: 'Navegação Inferior',
              type: 'bottom_nav',
              category: 'navigation',
              x: 0,
              y: 780,
              width: 393,
              height: 72,
              rotation: 0,
              zIndex: 20,
              opacity: 1,
              locked: true,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              fontFamily: 'Inter',
              fontSize: 12,
              fontWeight: '500',
              color: '#2563EB',
              textAlign: 'center',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#FFFFFF',
              items: ['Início', 'Categorias', 'Carrinho', 'Perfil'],
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'solid', color: '#F1F5F9', width: 1, radiusTopLeft: 20, radiusTopRight: 20, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: false },
              shadow: { enabled: true, color: 'rgba(0,0,0,0.06)', x: 0, y: -4, blur: 16, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
          ],
        },
        {
          id: 'scr_detail',
          name: 'Detalhes do Produto',
          backgroundColor: '#FFFFFF',
          isInitialScreen: false,
          components: [
            {
              id: 'c_det_topbar',
              name: 'Voltar Top Bar',
              type: 'top_app_bar',
              category: 'navigation',
              x: 0,
              y: 50,
              width: 393,
              height: 64,
              rotation: 0,
              zIndex: 10,
              opacity: 1,
              locked: true,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              fontFamily: 'Inter',
              fontSize: 18,
              fontWeight: '600',
              color: '#0F172A',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#FFFFFF',
              content: 'Detalhes do Tênis',
              iconName: 'ArrowLeft',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'solid', color: '#F1F5F9', width: 1, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'go_back' },
            },
            {
              id: 'c_det_img',
              name: 'Imagem Grande Tênis',
              type: 'image',
              category: 'basic',
              x: 20,
              y: 124,
              width: 353,
              height: 260,
              rotation: 0,
              zIndex: 5,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              fontFamily: 'Inter',
              fontSize: 14,
              fontWeight: '400',
              color: '#0F172A',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#F8FAFC',
              imageSrc: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
              objectFit: 'cover',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 20, radiusTopRight: 20, radiusBottomRight: 20, radiusBottomLeft: 20, isRadiusLinked: true },
              shadow: { enabled: true, color: 'rgba(0,0,0,0.08)', x: 0, y: 6, blur: 16, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_det_title',
              name: 'Título Detalhes',
              type: 'text',
              category: 'basic',
              x: 20,
              y: 400,
              width: 353,
              height: 32,
              rotation: 0,
              zIndex: 5,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: 'Tênis Urban Runner Pro 2026',
              fontFamily: 'Inter',
              fontSize: 22,
              fontWeight: '700',
              color: '#0F172A',
              textAlign: 'left',
              letterSpacing: -0.5,
              lineHeight: 1.2,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_det_price',
              name: 'Preço Grande',
              type: 'text',
              category: 'basic',
              x: 20,
              y: 436,
              width: 353,
              height: 36,
              rotation: 0,
              zIndex: 5,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: 'R$ 299,90',
              fontFamily: 'Inter',
              fontSize: 26,
              fontWeight: '800',
              color: '#2563EB',
              textAlign: 'left',
              letterSpacing: -0.5,
              lineHeight: 1.2,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_det_desc',
              name: 'Descrição',
              type: 'text',
              category: 'basic',
              x: 20,
              y: 480,
              width: 353,
              height: 60,
              rotation: 0,
              zIndex: 5,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: 'Desenvolvido para máximo conforto e estabilidade em corridas e uso diário. Cabedal respirável e solado amortecido.',
              fontFamily: 'Inter',
              fontSize: 14,
              fontWeight: '400',
              color: '#64748B',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.4,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_det_buybtn',
              name: 'Botão Adicionar Carrinho',
              type: 'button',
              category: 'basic',
              x: 20,
              y: 750,
              width: 353,
              height: 52,
              rotation: 0,
              zIndex: 10,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              content: 'Adicionar ao Carrinho 🛍️',
              fontFamily: 'Inter',
              fontSize: 16,
              fontWeight: '600',
              color: '#FFFFFF',
              textAlign: 'center',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#2563EB',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 16, radiusTopRight: 16, radiusBottomRight: 16, radiusBottomLeft: 16, isRadiusLinked: true },
              shadow: { enabled: true, color: 'rgba(37, 99, 235, 0.35)', x: 0, y: 6, blur: 16, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'show_toast', toastMessage: 'Produto adicionado ao carrinho!' },
            },
          ],
        },
      ],
    },
  },
  {
    id: 'banking_app',
    name: 'Finanças & Banco Digital',
    description: 'Dashboard de saldo, cartões de crédito, PIX rápido e extrato financeiro.',
    category: 'Finanças',
    previewUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=500&auto=format&fit=crop&q=80',
    project: {
      id: 'proj_banking',
      name: 'BankPay Mobile App',
      version: '1.0.0',
      device: defaultDevice,
      updatedAt: new Date().toISOString(),
      activeScreenId: 'scr_wallet',
      assets: [],
      screens: [
        {
          id: 'scr_wallet',
          name: 'Minha Carteira',
          backgroundColor: '#0F172A',
          isInitialScreen: true,
          components: [
            // User Header Row
            {
              id: 'c_b_avatar',
              name: 'Avatar Usuário',
              type: 'avatar',
              category: 'basic',
              x: 20,
              y: 60,
              width: 52,
              height: 52,
              rotation: 0,
              zIndex: 10,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              imageSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
              backgroundColor: '#334155',
              fontFamily: 'Inter',
              fontSize: 14,
              fontWeight: '400',
              color: '#FFFFFF',
              textAlign: 'center',
              letterSpacing: 0,
              lineHeight: 1,
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'solid', color: '#38BDF8', width: 2, radiusTopLeft: 26, radiusTopRight: 26, radiusBottomRight: 26, radiusBottomLeft: 26, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_b_greeting',
              name: 'Saudação',
              type: 'text',
              category: 'basic',
              x: 84,
              y: 64,
              width: 200,
              height: 22,
              rotation: 0,
              zIndex: 10,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: 'Olá, Mariana 👋',
              fontFamily: 'Inter',
              fontSize: 16,
              fontWeight: '700',
              color: '#F8FAFC',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_b_subgreeting',
              name: 'Subtitulo',
              type: 'text',
              category: 'basic',
              x: 84,
              y: 88,
              width: 200,
              height: 18,
              rotation: 0,
              zIndex: 10,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: 'Conta Premium #9421',
              fontFamily: 'Inter',
              fontSize: 12,
              fontWeight: '400',
              color: '#94A3B8',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            // Credit Card Box
            {
              id: 'c_b_card',
              name: 'Cartão de Crédito',
              type: 'container',
              category: 'layout',
              x: 20,
              y: 130,
              width: 353,
              height: 200,
              rotation: 0,
              zIndex: 8,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              fontFamily: 'Inter',
              fontSize: 14,
              fontWeight: '400',
              color: '#FFFFFF',
              textAlign: 'left',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#0284C7',
              gradient: { enabled: true, type: 'linear', angle: 135, startColor: '#0284C7', endColor: '#4338CA' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 24, radiusTopRight: 24, radiusBottomRight: 24, radiusBottomLeft: 24, isRadiusLinked: true },
              shadow: { enabled: true, color: 'rgba(2, 132, 199, 0.4)', x: 0, y: 12, blur: 24, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_b_bal_label',
              name: 'Label Saldo',
              type: 'text',
              category: 'basic',
              x: 44,
              y: 154,
              width: 200,
              height: 20,
              rotation: 0,
              zIndex: 9,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: 'SALDO DISPONÍVEL',
              fontFamily: 'Inter',
              fontSize: 11,
              fontWeight: '600',
              color: '#BAE6FD',
              textAlign: 'left',
              letterSpacing: 1,
              lineHeight: 1.2,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_b_bal_val',
              name: 'Valor Saldo',
              type: 'text',
              category: 'basic',
              x: 44,
              y: 178,
              width: 280,
              height: 40,
              rotation: 0,
              zIndex: 9,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: 'R$ 14.850,00',
              fontFamily: 'Inter',
              fontSize: 32,
              fontWeight: '800',
              color: '#FFFFFF',
              textAlign: 'left',
              letterSpacing: -0.5,
              lineHeight: 1.2,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            {
              id: 'c_b_card_num',
              name: 'Número Cartão',
              type: 'text',
              category: 'basic',
              x: 44,
              y: 280,
              width: 280,
              height: 24,
              rotation: 0,
              zIndex: 9,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 0,
              paddingRight: 0,
              paddingBottom: 0,
              paddingLeft: 0,
              content: '•••• •••• •••• 8842',
              fontFamily: 'Fira Code',
              fontSize: 16,
              fontWeight: '500',
              color: '#E0F2FE',
              textAlign: 'left',
              letterSpacing: 2,
              lineHeight: 1.2,
              backgroundColor: 'transparent',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 0, radiusTopRight: 0, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            // Pix Action Button
            {
              id: 'c_b_pix_btn',
              name: 'Botão Área PIX',
              type: 'button',
              category: 'basic',
              x: 20,
              y: 350,
              width: 168,
              height: 52,
              rotation: 0,
              zIndex: 8,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              content: '⚡ Área PIX',
              fontFamily: 'Inter',
              fontSize: 15,
              fontWeight: '600',
              color: '#FFFFFF',
              textAlign: 'center',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#10B981',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'none', color: '', width: 0, radiusTopLeft: 14, radiusTopRight: 14, radiusBottomRight: 14, radiusBottomLeft: 14, isRadiusLinked: true },
              shadow: { enabled: true, color: 'rgba(16, 185, 129, 0.3)', x: 0, y: 6, blur: 16, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'show_toast', toastMessage: 'Acessando transferência PIX...' },
            },
            {
              id: 'c_b_pay_btn',
              name: 'Botão Pagar Boleto',
              type: 'button',
              category: 'basic',
              x: 204,
              y: 350,
              width: 168,
              height: 52,
              rotation: 0,
              zIndex: 8,
              opacity: 1,
              locked: false,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              content: '📄 Pagar Conta',
              fontFamily: 'Inter',
              fontSize: 15,
              fontWeight: '600',
              color: '#38BDF8',
              textAlign: 'center',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#1E293B',
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'solid', color: '#334155', width: 1, radiusTopLeft: 14, radiusTopRight: 14, radiusBottomRight: 14, radiusBottomLeft: 14, isRadiusLinked: true },
              shadow: { enabled: false, color: '', x: 0, y: 0, blur: 0, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
            // Bottom Nav
            {
              id: 'c_b_nav',
              name: 'Navegação Finanças',
              type: 'bottom_nav',
              category: 'navigation',
              x: 0,
              y: 780,
              width: 393,
              height: 72,
              rotation: 0,
              zIndex: 20,
              opacity: 1,
              locked: true,
              hidden: false,
              paddingTop: 8,
              paddingRight: 8,
              paddingBottom: 8,
              paddingLeft: 8,
              fontFamily: 'Inter',
              fontSize: 12,
              fontWeight: '500',
              color: '#38BDF8',
              textAlign: 'center',
              letterSpacing: 0,
              lineHeight: 1.2,
              backgroundColor: '#1E293B',
              items: ['Extrato', 'Cartões', 'PIX', 'Investir'],
              gradient: { enabled: false, type: 'linear', angle: 0, startColor: '', endColor: '' },
              border: { style: 'solid', color: '#334155', width: 1, radiusTopLeft: 20, radiusTopRight: 20, radiusBottomRight: 0, radiusBottomLeft: 0, isRadiusLinked: false },
              shadow: { enabled: true, color: 'rgba(0,0,0,0.4)', x: 0, y: -4, blur: 16, spread: 0, inset: false },
              backdropBlur: 0,
              interaction: { onClickAction: 'none' },
            },
          ],
        },
      ],
    },
  },
];
